---
title: "Module 2, Assignment 2"
author: "Ellen Bledsoe"
date: "2023-02-23"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

1.  

```{r messsage = FALSE}
library(tidyverse)
```

2.

    ```{r}
    growth <- read_csv("../data/tilapia_growth.csv")
    head(growth)
    tail(growth)
    ```


5.

    ```{r}
    growth <- growth %>%
      mutate(day_30_weight_kg = day_30_weight / 1000)
    ```

6.

    ```{r}
    growth_by_treatment <- growth %>%
      group_by(perc_soy_protein) %>%
      summarize(mean_weight_kg = mean(day_30_weight_kg))
    growth_by_treatment
    ```

7.

    ```{r}
    ggplot(growth, aes(perc_soy_protein, day_30_weight_kg)) +
      geom_point() +
      labs(x = "Percent Diet Comprised of Soy Protein",
       y = "Tilapia Weight at 30 Days (kg)") +
      theme_light()
    ```

8.

    ```{r}
    growth_by_treatment_and_temp <- growth %>%
      group_by(perc_soy_protein, tank_category) %>%
      summarise(mean_weight_kg = mean(day_30_weight_kg))
    growth_by_treatment_and_temp
    ```

9.

    ```{r}
    ggplot(growth, aes(avg_tank_temp, day_30_weight_kg)) +
      geom_point() +
      labs(x = "Average Tank Temperature (C)",
       y = "Tilapia Weight at 30 Days (kg)") +
      theme_light()
    ```
