---
title: "Module 3 Assignment 1"
author: "Ellen Bledsoe"
date: '2023-03-23'
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r message = FALSE}
library(tidyverse)
turbines <- read_csv("../data/wind_turbines.csv")
```


2.  

```{r}
turbine_summary <- turbines %>% 
  group_by(manufacturer) %>% 
  summarise(mean_wind_speed = mean(wind_speed),
            mean_power = mean(power_output))
turbine_summary
```

3.  

```{r}
ggplot(turbines, aes(power_output, color = manufacturer, fill = manufacturer)) +
  geom_density(alpha = 0.5) +
  geom_vline(data = turbine_summary, aes(xintercept = mean_power, color = manufacturer)) +
  labs(x = "Power Output",
       y = "Density",
       color = "Manufacturer",
       fill = "Manufacturer") +
  theme_classic()
```

4.  

```{r}
ggplot(turbines, aes(manufacturer, wind_speed)) +
  geom_boxplot() +
  geom_jitter(width = 0.1, alpha = 0.5) +
  labs(x = "Maker",
       y = "Wind Speed (km/hr)") +
  theme_classic()
```

7.  

```{r}
t.test(data = turbines, power_output ~ manufacturer)
```


9.  

```{r}
t.test(data = turbines, wind_speed ~ manufacturer)
```
